GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY2MDM2MTQ2MywiZXhwIjoxNjYwMzYxNDc4fQ.t59N8KoYk62DQ3ZpFB_qTGHCOwD1TZYiOrqwHnovlVE
###

POST http://localhost:5000/token
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY2MDM2MTg4NX0.uCx2KfGrdRp4SL7aovNaZ0gukSju50yN2h4k6epIWIk"
}

###

POST http://localhost:5000/login
content-type: application/json

{
    "username": "Kyle"
}

###

DELETE http://localhost:5000/logout
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY2MDM2MTg4NX0.uCx2KfGrdRp4SL7aovNaZ0gukSju50yN2h4k6epIWIk"
}
